# Generated by Django 5.2.5 on 2025-12-07 23:46

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_category_custompermissions_project_unit_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('front_pocket', models.BooleanField(default=True)),
                ('side_pocket', models.BooleanField(default=False)),
                ('coller', models.CharField(blank=True, max_length=100)),
                ('sleve_length', models.CharField(blank=True, max_length=100)),
                ('cuff', models.CharField(blank=True, max_length=100)),
                ('chest', models.CharField(blank=True, max_length=100)),
                ('shirt_kera_round', models.BooleanField(default=True)),
                ('shirt_kera', models.CharField(blank=True, max_length=100)),
                ('shirt_length', models.CharField(blank=True, max_length=100)),
                ('shalwar_length', models.CharField(blank=True, max_length=100)),
                ('shalwar_hole', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('filtered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='store_issue_note',
            name='products',
        ),
        migrations.RemoveField(
            model_name='store_issue_product',
            name='product',
        ),
        migrations.RemoveField(
            model_name='store_issue_request',
            name='products',
        ),
        migrations.RemoveField(
            model_name='store_issue_request_product',
            name='product',
        ),
        migrations.RemoveField(
            model_name='store_issue_note',
            name='project',
        ),
        migrations.RemoveField(
            model_name='store_issue_request',
            name='project',
        ),
        migrations.RemoveField(
            model_name='store_issue_note',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='store_issue_note',
            name='request',
        ),
        migrations.RemoveField(
            model_name='store_issue_product',
            name='store_issue_note',
        ),
        migrations.RemoveField(
            model_name='store_issue_request',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='store_issue_request_product',
            name='store_issue_request',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.AddField(
            model_name='task',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tasks', to='tasks.customer'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Store_Issue_Note',
        ),
        migrations.DeleteModel(
            name='Store_Issue_Product',
        ),
        migrations.DeleteModel(
            name='Store_Issue_Request',
        ),
        migrations.DeleteModel(
            name='Store_Issue_Request_Product',
        ),
    ]
