# Generated by Django 5.2.5 on 2025-12-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_customer_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Adress',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='Phome_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
