# Generated by Django 5.2.5 on 2025-12-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_customer_adress_customer_phome_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='shalwar_pocket',
            field=models.BooleanField(default=True),
        ),
    ]
