# Generated by Django 5.2.5 on 2025-12-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_customer_shalwar_pocket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='front_pocket',
            new_name='front_pocket_right',
        ),
        migrations.AddField(
            model_name='customer',
            name='side_pocke_leftt',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='sleve_hole',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='tera',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
