# Generated by Django 5.2.5 on 2025-12-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_rename_front_pocket_customer_front_pocket_right_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='cuff',
            new_name='belly',
        ),
        migrations.AddField(
            model_name='customer',
            name='cuff_hole',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='cuff_width',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
