# Generated by Django 5.2.5 on 2025-12-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_rename_cuff_customer_belly_customer_cuff_hole_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='side_pocke_leftt',
            field=models.BooleanField(default=False),
        ),
    ]
