# Generated by Django 5.2.5 on 2025-12-08 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_customer_side_pocke_leftt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='side_pocke_leftt',
            new_name='side_pocke_left',
        ),
    ]
