# Generated by Django 5.2.5 on 2025-12-08 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_rename_side_pocke_leftt_customer_side_pocke_left'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='side_pocke_left',
            new_name='side_pocket_left',
        ),
    ]
