# Generated by Django 5.2.5 on 2025-12-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_rename_side_pocke_left_customer_side_pocket_left'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='side_pocket',
            new_name='side_pocket_right',
        ),
        migrations.AddField(
            model_name='customer',
            name='front_pocket_left',
            field=models.BooleanField(default=True),
        ),
    ]
