# Generated by Django 5.2.5 on 2025-12-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_rename_side_pocket_customer_side_pocket_right_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='front_pocket_right',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='side_pocket_right',
            field=models.BooleanField(default=True),
        ),
    ]
