# Generated by Django 5.2.5 on 2025-12-08 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_task_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Customer',
            new_name='customer',
        ),
    ]
