# Generated by Django 5.2.7 on 2025-12-09 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0015_rename_customer_task_customer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
    ]
