# Generated by Django 5.2.7 on 2025-12-10 06:29

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0016_delete_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="belly",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="chest",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="coller",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="cuff_hole",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="cuff_width",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="front_pocket_left",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="front_pocket_right",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="shalwar_hole",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="shalwar_length",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="shalwar_pocket",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="shirt_kera",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="shirt_kera_round",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="shirt_length",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="side_pocket_left",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="side_pocket_right",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="sleve_hole",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="sleve_length",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="tera",
        ),
        migrations.AlterField(
            model_name="task",
            name="assigned_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Coat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(default="Coat", max_length=100)),
                ("waist", models.CharField(blank=True, max_length=100, null=True)),
                ("chest", models.CharField(blank=True, max_length=100)),
                (
                    "sleve_length",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("sleve_hole", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "Customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="coat",
                        to="tasks.customer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("filtered", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Shalwar_Qameez",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(default="Shalwar Qameez", max_length=100)),
                ("front_pocket_right", models.BooleanField(default=False)),
                ("front_pocket_left", models.BooleanField(default=True)),
                ("side_pocket_right", models.BooleanField(default=True)),
                ("side_pocket_left", models.BooleanField(default=False)),
                ("coller", models.CharField(blank=True, max_length=100)),
                ("sholder_width", models.CharField(blank=True, max_length=100)),
                ("sleve_length", models.CharField(blank=True, max_length=100)),
                ("sleve_hole", models.CharField(blank=True, max_length=100)),
                ("cuff_hole", models.CharField(blank=True, max_length=100)),
                ("cuff_width", models.CharField(blank=True, max_length=100)),
                ("chest", models.CharField(blank=True, max_length=100)),
                ("belly", models.CharField(blank=True, max_length=100)),
                ("shirt_kera_round", models.BooleanField(default=True)),
                ("shirt_kera", models.CharField(blank=True, max_length=100)),
                ("shirt_length", models.CharField(blank=True, max_length=100)),
                ("shalwar_length", models.CharField(blank=True, max_length=100)),
                ("shalwar_hole", models.CharField(blank=True, max_length=100)),
                ("shalwar_pocket", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "Customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="shalwar_qameez",
                        to="tasks.customer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("filtered", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Sheer_Vani",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(default="Shirt", max_length=100)),
                ("coller", models.CharField(blank=True, max_length=100)),
                ("waist", models.CharField(blank=True, max_length=100, null=True)),
                ("chest", models.CharField(blank=True, max_length=100)),
                ("length", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "sleve_length",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("sleve_hole", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "sholder_width",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "Customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="sheer_vani",
                        to="tasks.customer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("filtered", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Shirt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(default="Shirt", max_length=100)),
                ("front_pocket_right", models.BooleanField(default=False)),
                ("front_pocket_left", models.BooleanField(default=True)),
                ("coller", models.CharField(blank=True, max_length=100)),
                ("tera", models.CharField(blank=True, max_length=100)),
                ("sleve_length", models.CharField(blank=True, max_length=100)),
                ("sleve_hole", models.CharField(blank=True, max_length=100)),
                ("cuff_hole", models.CharField(blank=True, max_length=100)),
                ("cuff_width", models.CharField(blank=True, max_length=100)),
                ("chest", models.CharField(blank=True, max_length=100)),
                ("belly", models.CharField(blank=True, max_length=100)),
                ("shirt_length", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "Customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="shirt",
                        to="tasks.customer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("filtered", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Trouser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(default="Shirt", max_length=100)),
                ("waist", models.CharField(blank=True, max_length=100, null=True)),
                ("hips", models.CharField(blank=True, max_length=100, null=True)),
                ("thigh", models.CharField(blank=True, max_length=100, null=True)),
                ("calf", models.CharField(blank=True, max_length=100, null=True)),
                ("length", models.CharField(blank=True, max_length=100, null=True)),
                ("knee", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "sitting_crotch_depth",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("outseam", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "Customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="trouser",
                        to="tasks.customer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("filtered", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Vase_Coat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(default="Shirt", max_length=100)),
                ("coller", models.CharField(blank=True, max_length=100)),
                ("waist", models.CharField(blank=True, max_length=100, null=True)),
                ("chest", models.CharField(blank=True, max_length=100)),
                ("length", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "Customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="vase_coat",
                        to="tasks.customer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("filtered", django.db.models.manager.Manager()),
            ],
        ),
    ]
