# Generated by Django 5.2.7 on 2025-12-10 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0018_shirt_shalwar_hole_alter_coat_chest_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coat",
            old_name="Customer",
            new_name="customer",
        ),
        migrations.RenameField(
            model_name="shalwar_qameez",
            old_name="Customer",
            new_name="customer",
        ),
        migrations.RenameField(
            model_name="sheer_vani",
            old_name="Customer",
            new_name="customer",
        ),
        migrations.RenameField(
            model_name="shirt",
            old_name="Customer",
            new_name="customer",
        ),
        migrations.RenameField(
            model_name="trouser",
            old_name="Customer",
            new_name="customer",
        ),
        migrations.RenameField(
            model_name="vase_coat",
            old_name="Customer",
            new_name="customer",
        ),
    ]
