# Generated by Django 5.2.7 on 2025-12-16 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0019_rename_customer_coat_customer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="Phome_number",
            new_name="phone_number",
        ),
    ]
