# Generated by Django 5.2.7 on 2025-12-17 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0020_rename_phome_number_customer_phone_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="Adress",
            new_name="address",
        ),
    ]
