# Generated by Django 5.2.7 on 2025-12-17 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0023_alter_custompermissions_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="custompermissions",
            options={
                "permissions": [
                    ("view_dashboard", "Can view dashboard"),
                    ("view_balance_sheet", "Can view balance sheet"),
                    ("view_store", "Can view store"),
                    ("view_reports", "Can view reports"),
                    ("view_inventory", "Can view inventory"),
                    ("view_measurements", "Can view measurements"),
                    ("add_measurements", "Can add measurements"),
                    ("change_measurements", "Can change measurements"),
                ]
            },
        ),
    ]
